### ISSUE TITLE
how to change the mode in my server?

### ISSUE THREAD

**Issue by KaguraXun** [magneticflux-/fabric-tree-chopper#29]
it alway work with single_mode

**Comment by magneticflux-** [comment]
The available chop modes are located here: https://github.com/magneticflux-/fabric-tree-chopper/blob/370e6178da863e0bfa9b260e336e4551d1d568ee/src/main/kotlin/com/skaggsm/treechoppermod/FabricTreeChopperConfig.kt#L17-L21

I'll update the readme with more detailed config instructions.
