### ISSUE TITLE
[Feature request] Avoid breaking Axe

### ISSUE THREAD

**Issue by TBG-FR** [magneticflux-/fabric-tree-chopper#44]
Hello there !

I've been trying various mods around the "tree chopping" problem, and yours is great because of the "natural leaves" recognition !
However, I think it misses a setting to avoid breaking the Axe (leaving it with 1 of durability), when you cut a big tree.
I think it may have to deal with BREAK_AFTER_CHOP or BREAK_MID_CHOP to choose if the tree should be left partially chopped or not.

Also, are you accepting pull request ? Maybe I could find some time and help you on that kind of improvement 😄 

Thanks in advance !

**Comment by magneticflux-** [comment]
I think #53 is a solid implementation of this idea. I'd love your feedback on the changes in this preview: [fabric-tree-chopper-0.7.3-SNAPSHOT.zip](https://github.com/magneticflux-/fabric-tree-chopper/files/7141667/fabric-tree-chopper-0.7.3-SNAPSHOT.zip). Let me know how it works for you!

**Comment by TBG-FR** [comment]
Sorry, I didn't had the time to check that yet, but thanks for the update and the fix !
