### ISSUE TITLE
Does not count toward statistics or scoreboards

### ISSUE THREAD

**Issue by RandomGgames** [magneticflux-/fabric-tree-chopper#49]
Love this mod, however there's one issue which most plugins like it have... They don't increase statistics/scoreboards!

The statistic I'm talking about would be the count of TYPE logs mined and for scoreboards, the criteria minecraft.mined:minecraft.TYPE_log, neither of which increase when the bottom block is broken.

**Comment by magneticflux-** [comment]
Good point! It seems relatively easy to do; I'll see if I can get a release done in a day or two.

**Comment by magneticflux-** [comment]
I think 84fdce31e15b11be967d6f15ac1804d11c048e29 should fix it. I think it should, but do you know if `player.incrementStat(Stats.MINED...)` also works for the criteria you mentioned?

If the fix works for you, I'll release it and Curseforge will probably publish it in under an hour.
