### ISSUE TITLE
Mod

### ISSUE THREAD

**Issue by SubiLover09** [magneticflux-/fabric-tree-chopper#65]
After I installed this mod, I noticed it doesn't work for me. Whenever I try to break down a tree, it breaks down like normal. Can someone help me? [UPDATE] Now i can't even get it to work in Forge Minecraft. It doesn't show the mods in the mod list, but it shows it in the mods folder in ".minecraft". I have no idea what's happening as this is my first time downloading mods. Please help?

**Comment by magneticflux-** [comment]
This mod is not a Forge mod, it is a Fabric mod. To use it, you must use the Fabric mod loader: https://fabricmc.net/
